name: Update README with Latest Repos

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Fetch Public Repos
        id: repos
        uses: octokit/request-action@v3
        with:
          route: GET /users/modhack2003/repos
          mediaType: '{"format":"json"}'
      - name: Render Recent Repos Markdown
        run: |
          echo "### Rendering newest repos..."
          repos=$(echo "${{ steps.repos.outputs.data }}" | jq -r '.[] | select(.fork == false) | "\u2022 [\(.name)](\(.html_url)) — \(.description // "No description")"' | head -n 5)
          echo "recent_repos<<EOF" >> README.md
          echo "$repos" >> README.md
          echo "EOF" >> README.md
      - name: Commit if Changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --quiet || git commit -m "Update README with latest repos"
          git push
